#!/usr/bin/env python3
"""Bulk shot generation for Tell-Tale Heart using Gemini image generation."""

import os
import time
import base64
from pathlib import Path
from google import genai
from google.genai import types

# --- Config ---
API_KEY = os.environ.get("GEMINI_API_KEY", "")
MODEL_ID = "gemini-2.5-flash-image"
OUTPUT_DIR = Path("generated_v2")
IMAGES_PER_PROMPT = 3
DELAY_BETWEEN_REQUESTS = 3
MAX_RETRIES = 3
RETRY_DELAY = 15

# --- Reference images ---
REF_NARRATOR = Path("narrator-ref.png")
REF_OLD_MAN = Path("old-man-ref.png")
REF_EYE = Path("eye-ref.png")
REF_BEDROOM = Path("bedroom-ref.png")

NARRATOR = "narrator"
OLD_MAN = "old_man"
EYE = "eye"
BEDROOM = "bedroom"

# --- All shots ---
SHOTS = [
    # NARRATOR SHOTS
    ("001", "A Victorian Gothic oil painting depicting a wide shot of a high-walled Victorian prison exercise yard. A tall gaunt man in a dark charcoal jacket walks slowly along the far grey stone wall, his back fully turned to the viewer, his figure small against the massive wall. The cobblestone floor stretches toward him. Two prisoner silhouettes stand blurred in the far background. The light is cold, flat, and overcast — no shadows, no warmth, only grey. Painted in Payne's grey and raw umber with visible expressive brushstrokes. The mood is bleak and contained. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("002", "A Victorian Gothic oil painting depicting a close-up portrait of a tall gaunt man with a hollow face, dark damp hair falling across his forehead, very deep-set eyes with heavy dark rings beneath them, sharp prominent cheekbones, thin dark stubble, wearing a worn dark charcoal jacket with lapels and a grey open-collar shirt. He is looking directly into the viewer's eyes. His expression is controlled, insistent, and urgent — a man who needs to be believed. A grey stone wall is blurred softly behind him. The light is cold and overcast, falling from above left. Captured with an 85mm portrait lens with shallow depth of field. Painted in Payne's grey and raw umber with visible expressive brushstrokes. Chiaroscuro lighting in the style of Caravaggio. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("003", "A Victorian Gothic oil painting depicting a medium close-up of a tall gaunt man with a hollow face, dark damp hair, deep-set ringed eyes, sharp cheekbones, dark stubble, dark charcoal jacket, grey open-collar shirt. He is shown in three-quarter profile facing the right side of the frame. A rough grey stone wall is pressed very close behind his shoulder, nearly touching it. His eyes are slightly downcast with an expression of precise, careful argument. The light is cold and flat, falling from above. Captured with an 85mm lens at a slight low angle looking up at him. Painted in Payne's grey and raw umber with thick visible brushstrokes. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("004", "A Victorian Gothic oil painting depicting an extreme close-up macro image of a man's ear and the side of his head in profile, pressed near a rough grey stone wall. The ear fills the centre of the frame. Heavy dark hair is visible above. The aged skin of the ear catches cold grey light. The expression of the face in profile: focused and deeply attentive, every faculty directed toward listening. Pure cold grey tones throughout. Thick textured impasto brushstrokes, Payne's grey palette. The mood is one of intense concentration. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("005", "A Victorian Gothic oil painting depicting a wide shot of a Victorian prison exercise yard. A tall gaunt man in a dark charcoal jacket stands completely still among other dark-clad prisoners who walk past him as blurred shapes. His head is very slightly tilted to one side as if catching a distant sound. He is the only completely still figure in the entire frame. Stone walls surround the yard. Cold overcast grey light. Captured with a 50mm lens at eye level. Painted in Payne's grey and raw umber with visible brushstrokes. The mood is one of eerie stillness within movement. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("006", "A Victorian Gothic oil painting depicting a close-up of a tall gaunt man with hollow cheeks, deep-set ringed eyes, dark damp hair, dark stubble, dark charcoal jacket, grey open-collar shirt. He is seated on a rough worn wooden bench pressed against a grey stone wall. One hand is raised with the palm open in mid-gesture, elbow on knee, leaning forward slightly. His expression is earnest and urgent — a man desperately needing to be understood and believed. The light is cold and grey, falling from above. Prisoners are blurred shapes in the background corridor behind him. Slightly elevated camera angle looking down at him. Oil painting, Payne's grey palette, visible brushstrokes. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("007", "A Victorian Gothic oil painting depicting a medium close-up of a tall gaunt man with hollow cheeks, deep-set ringed eyes, dark damp hair, dark stubble, dark charcoal jacket, grey shirt. He is leaning very slightly forward toward the viewer, both hands resting on his knees, his eyes looking directly and calmly into the frame. His expression is that of a man who has made a definitive decision and is entirely at peace with it. A grey stone wall is behind him, cold and flat. Eye level camera, 85mm lens. Payne's grey and raw umber oil painting with visible brushstrokes. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("013", "A Victorian Gothic oil painting depicting a medium close-up of a tall gaunt man with hollow cheeks, deep-set ringed eyes, dark damp hair, dark stubble, dark charcoal jacket, grey shirt. His expression shows controlled disgust — an involuntary narrowing of the eyes, a very slight tightening around the jaw. His gaze is directed slightly to the left of frame at something the viewer cannot see. Cold grey stone wall behind him, eye level camera, 85mm lens. Payne's grey oil painting palette with visible brushstrokes. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("014", "A Victorian Gothic oil painting depicting a close-up of a tall gaunt man with hollow cheeks, deep-set ringed eyes, dark damp hair, dark stubble, dark charcoal jacket, grey shirt. He is shown in three-quarter profile facing the right side of the frame. A private decision has just arrived in his expression — there is resolution in his eyes and a controlled neutral set to the corners of his mouth. The look of a man who has just chosen his course. Cold grey wall behind him. Slight low angle camera, 85mm lens. Payne's grey oil painting with visible brushstrokes. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("015", "A Victorian Gothic oil painting depicting a medium close-up of a tall gaunt man with hollow cheeks, deep-set ringed eyes, dark damp hair, dark stubble, dark charcoal jacket, grey shirt. He is seated on a bench with his back very straight, both hands placed deliberately and firmly on his knees. His posture radiates composed self-satisfaction — the posture of a man describing a personal mastery. Other prisoners are blurred dark shapes in the background. Cold grey light. Low angle camera looking up at him. Payne's grey oil painting. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("016", "A Victorian Gothic oil painting depicting an extreme close-up macro image of a man's gaunt pale hands, fingers fully interlaced and clasped together. Dark charcoal jacket sleeves are visible at both wrists. Every finger is precisely placed. The grip is deliberate, controlled, and ceremonial — like a man completing a private ritual. Cold flat grey light. No face visible — only the hands fill the frame. Thick textured brushstrokes in ochre flesh tones and Payne's grey. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("018", "A Victorian Gothic oil painting depicting an extreme close-up macro image of gaunt pale fingers closed very lightly around a worn iron door latch. Near-total darkness surrounds the hand. At the very base of the door below: a single hairline thread of warm amber-gold light bleeds through the gap beneath the door, the only light in the composition. The fingers rest on the latch with extreme, almost ceremonial lightness. Near-monochrome Payne's grey palette with a single amber trace. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("020", "A Victorian Gothic oil painting depicting an extreme close-up macro image of two gaunt pale hands holding a completely closed dark Victorian tin lantern against a pure black background. The lantern panel is shut on every side — no light escapes from any seam. The hands hold it with absolute surgical care. Near-total darkness, the hands barely visible against the black. Only the faintest ambient light catches the edges of the knuckles. Oil painting in near-monochrome darkness. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("022", "A Victorian Gothic oil painting depicting a medium shot looking from inside a dark stone corridor toward an open bedroom doorway. A tall gaunt man stands in the doorway as a near-silhouette, his dark jacket and gaunt profile barely readable against the warm amber light that fills the bedroom beyond. Only the sharp edge of his cheekbone catches the amber backlight as a bright sliver. He stands completely still facing the bedroom. The corridor behind him is near-black. The doorway ahead is a warm amber rectangle. Deep Caravaggio-style chiaroscuro — near-black foreground, warm amber background. 35mm lens, low angle. Oil painting. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("025", "A Victorian Gothic oil painting depicting a medium close-up of a tall gaunt man with hollow cheeks, deep-set ringed eyes, dark damp hair, dark stubble, dark charcoal jacket, grey shirt — shown in strict profile facing the right side of the frame. His jaw is set firmly. His eyes are fixed on something internal, not visible in the frame. His expression is that of controlled frustration — a man whose careful plan has encountered an obstacle. Cold grey prison wall directly behind him. Low angle camera. Payne's grey oil painting. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("026", "A Victorian Gothic oil painting depicting a close-up of a tall gaunt man with hollow cheeks, deep-set ringed eyes, dark damp hair, dark stubble, dark charcoal jacket, grey shirt — looking directly into the viewer's eyes with a slight low angle camera. His expression is that of a man making an extremely precise distinction, explaining something with careful controlled precision. Cold grey stone wall behind him. 85mm portrait lens. Payne's grey oil painting with visible brushstrokes. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("028", "A Victorian Gothic oil painting depicting a medium shot of a tall gaunt man with hollow cheeks, deep-set ringed eyes, dark damp hair, dark stubble, dark charcoal jacket — in the physical act of rising from a rough wooden bench. Both his hands are pressed down onto the bench surface, his body fully upright. His head is raised and his eyes are focused on a specific point in the middle distance — the expression of a man who has just reached a firm decision. Cold grey light. Low angle camera, 50mm lens. Payne's grey oil painting. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("030", "A Victorian Gothic oil painting depicting an extreme close-up macro image from floor level looking horizontally. A single dark leather shoe on a pale wooden floorboard — the sole is barely raised off the surface, lifted only a few millimetres. The grain of the pale warm wood is visible beneath. Warm amber light comes from ahead, illuminating the floorboard surface. The dark shoe against the warm wood. Only the shoe and the floor — no other elements. Macro lens at floor level. Warm amber oil painting palette. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("031", "A Victorian Gothic oil painting depicting an extreme close-up macro image. One human eye is visible through a narrow vertical crack between two dark wooden door panels — the crack is only about 5 millimetres wide. The eye: dark iris, the gaunt hollow-cheeked skin around it. Warm amber candlelight from inside the room illuminates the eye from the left side. The two dark wooden door panels frame the eye on either side, filling most of the frame. The eye is absolutely still, watching, completely predatory — no fear, no uncertainty. Oil painting. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("032", "A Victorian Gothic oil painting depicting a close-up of a tall gaunt man with hollow cheeks, deep-set ringed eyes, dark damp hair, dark stubble, dark charcoal jacket, grey shirt. His expression is one of private triumph — his eyes are very slightly wider than neutral, a fractional tightening of the facial muscles reads as controlled excitement. He is not smiling — it is something more dangerous and deliberate than a smile. Low angle camera, 85mm lens. Cold grey. Oil painting. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("035", "A Victorian Gothic oil painting depicting a close-up from inside a Victorian bedroom at low angle looking toward a partly open door. Through the partial opening: the gaunt face of a tall man in profile, dark hair, pressed close to the gap — he is leaning his head through the door. Both his hands are visible below his face, holding a completely closed dark tin lantern. He is pressed against the narrow opening. Near-darkness on both sides of the door frame. Only the faintest amber trace of light from inside the room. 50mm lens from inside the room looking toward him. Oil painting. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("038", "A Victorian Gothic oil painting depicting a medium shot from inside a Victorian bedroom, camera at floor level looking up toward the doorway. A tall gaunt man stands in the doorway with one foot just across the threshold — completely frozen in position. He is a near-silhouette against the slightly less dark corridor behind him. His right hand is concealed behind his back. His face is in three-quarter shadow. He is a statue. The warm bedroom darkness is in front of him, cold corridor darkness behind. 35mm lens, floor-level low angle. Oil painting. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("050", "A Victorian Gothic oil painting depicting a medium close-up of a tall gaunt man with hollow cheeks, deep-set ringed eyes, dark damp hair, dark stubble, dark charcoal jacket. His expression is one of detached recognition — he has encountered this before and knows exactly what it is. There is no triumph in his face, only the cold precision of a man identifying a known phenomenon. Warm amber underlight from a lantern held below frame casts shadows upward across his face. Low angle camera, 85mm. Oil painting. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("051", "A Victorian Gothic oil painting depicting a medium shot of a tall gaunt man with hollow cheeks, deep-set ringed eyes, dark damp hair, dark stubble, dark charcoal jacket — seated in prison with both hands clasped in his lap and his head bowed slightly. The posture of deep memory. Cold grey light. Eye level camera, 85mm. Payne's grey oil painting. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("053", "A Victorian Gothic oil painting depicting a close-up of a tall gaunt man with hollow cheeks, deep-set ringed eyes, dark damp hair, dark stubble, dark charcoal jacket — looking directly into the viewer's eyes. The controlled precision of his usual expression has fractionally loosened. Something personal has surfaced — he is making an admission about himself that costs him something. His deep-set eyes carry visible weight. Cold grey. Direct address, 85mm lens. Oil painting. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("061", "A Victorian Gothic oil painting depicting a medium close-up of a tall gaunt man with hollow cheeks, deep-set ringed eyes, dark damp hair, dark stubble, dark charcoal jacket. His head is tilted very slightly to one side — the posture of intense listening. His expression holds a question: does anyone else hear what he hears? Cold grey light from behind, a trace of warm amber from below. Slight low angle camera, 85mm. Oil painting. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("063", "A Victorian Gothic oil painting depicting an extreme close-up macro bird's-eye view looking straight down at pale Victorian wooden floorboards. Two dark leather shoes are on the floor — one pressed firmly down, the other mid-lift with the sole barely clearing the surface. Warm amber candlelight illuminates the grain of the pale wood beneath the shoes. Only the shoes and the floor — the frame fills entirely with this detail. Oil painting, warm amber. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("065", "A Victorian Gothic oil painting depicting a medium shot from behind and below of a tall gaunt man — seen only as a dark silhouette from the back. A plain wooden chair is raised above his head with both arms fully extended upward. Against the warm amber candlelight behind him his silhouette is stark and dramatic. The Victorian bedroom surrounds him: peeling wallpaper, a bed visible at the right. The pose is explosive, arms fully up. 35mm lens from behind and low. Strong silhouette. Oil painting. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("068", "A Victorian Gothic oil painting depicting a medium shot from behind and slightly elevated. A tall gaunt man in a dark charcoal jacket stands with his back entirely to the viewer. He is looking down at the pale wooden floor beside an empty bed — the blue-grey coverlet is pulled and disturbed, the bed empty. The man's posture is one of absolute completion — the stillness of a finished task. Warm amber candlelight. 35mm lens from behind. Oil painting. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("071", "A Victorian Gothic oil painting depicting an extreme close-up macro image of a man's ear and the side of his head — but unlike shot 004, this one is angled sharply downward toward the floor, as if the ear is being pressed toward the ground to listen for sounds beneath. His eye is barely visible above the ear, looking sideways. At the very bottom edge of the frame: pale wooden floorboards. Warm amber light from below. Oil painting. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("072", "A Victorian Gothic oil painting depicting an extreme close-up macro image of a gaunt pale hand pressed completely flat on a surface — fingers spread wide, palm face-down, the hand absolutely still. The surface beneath is implied to be a chest. Warm amber candlelight from the right side illuminates the thin skin and prominent tendons on the back of the hand. Only the hand fills the frame. Oil painting. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("073", "A Victorian Gothic oil painting depicting a close-up of a tall gaunt man with hollow cheeks, deep-set ringed eyes, dark damp hair, dark charcoal jacket — looking downward, his face seen from slightly above in a high angle. His expression is clinical and confirming — not triumphant, not emotional. The expression of a professional confirming a result. His eyes are directed at something below the frame. Amber light from the side. High angle camera. 85mm. Oil painting. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("075", "A Victorian Gothic oil painting depicting a medium close-up of a tall gaunt man with hollow cheeks, deep-set ringed eyes, dark damp hair, dark stubble, dark charcoal jacket — looking directly into the viewer's eyes. His expression is one of absolute calm certainty — the challenge issued. He is about to prove something and he already knows the outcome. His eyes are direct, unwavering, and completely composed. Cold grey. Direct address, 85mm, slight low angle. Oil painting. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("076", "A Victorian Gothic oil painting depicting an extreme close-up macro image from slightly above, looking down. Two gaunt pale hands are gripping the edges of a pale wooden floorboard — fingers wedged into the gap between boards, the board beginning to lift at one edge. The darkness of the space beneath the floor is just barely becoming visible as a thin dark line. Warm amber candlelight. Oil painting. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("078", "A Victorian Gothic oil painting depicting an extreme close-up macro bird's-eye view looking straight down. Two gaunt pale hands are pressing the last wooden floorboard flat — both palms face-down, applying firm even pressure. The board is perfectly flush with the neighbouring boards on both sides. The floor looks completely undisturbed. The hands are pressed flat. Oil painting, warm amber light. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("080", "A Victorian Gothic oil painting depicting a close-up of two hands held up with palms facing toward the viewer — examined, clean, not a mark on them. The candlelight behind the hands makes the thin skin glow very slightly amber, the bones and tendons visible through it. The face above the hands — the tall gaunt narrator — shows quiet satisfaction in the clean evidence. 85mm lens, eye level. Warm amber. Oil painting. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("085", "A Victorian Gothic oil painting depicting a medium shot from the side of a tall gaunt man with hollow cheeks, deep-set ringed eyes, dark damp hair, dark charcoal jacket — standing at an open Victorian front door. He has one arm extended outward in a welcoming gesture, ushering in three dark-uniformed Victorian police officer silhouettes who are entering from the right side of the frame. His expression is unhurried, welcoming, entirely at ease — the perfect innocent householder. 50mm lens from the side. Oil painting. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("086", "A Victorian Gothic oil painting depicting a medium close-up of a tall gaunt man with hollow cheeks, deep-set ringed eyes, dark damp hair, dark stubble, dark charcoal jacket — seated in a plain wooden chair. Both hands rest on the wooden armrests. His expression: deliberate ease, controlled composure, almost imperceptibly smug. His eyes are focused and direct. Three blurred dark-uniformed Victorian police officers are visible as soft shapes behind him. A small candle flame is visible near the bottom edge of the frame. Low angle camera looking up at him, 85mm lens. Warm amber light from below. Oil painting. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("087", "A Victorian Gothic oil painting depicting a wide shot from the corner of a Victorian bedroom. The tall gaunt narrator in his dark charcoal jacket stands in the centre of the room making a welcoming gesture with one arm. Three blurred dark-uniformed Victorian police officers stand near the bedroom doorway at the right side of the frame. The narrator is sharply in focus, the officers slightly soft. The pale wooden floorboards are undisturbed. Warm amber candlelight. 24mm lens, from the corner. Oil painting. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("088", "A Victorian Gothic oil painting depicting a wide shot from inside a Victorian bedroom looking toward the open doorway. The tall gaunt narrator stands in the doorway with one arm extended, presenting the room — the gesture of a man showing that everything is completely ordinary and in order. The bedroom behind him is tidy — the ball-top bed made, the coverlet smooth, everything in its correct place. 35mm lens from inside the room looking toward him. Oil painting. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("089", "A Victorian Gothic oil painting depicting a medium shot of a tall gaunt man in a dark charcoal jacket in a Victorian bedroom — pulling a plain wooden chair across the floor toward a sitting position, the gesture of a generous host providing seating. His expression is helpful, engaged, and entirely at ease. One blurred dark-uniformed officer is seated in the background at the right. Warm amber candlelight. 50mm lens. Oil painting. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("090", "A Victorian Gothic oil painting depicting a medium close-up of a tall gaunt man with hollow cheeks, deep-set ringed eyes, dark damp hair, dark stubble, dark charcoal jacket — seated with both hands resting on the armrests of a wooden chair. His expression: deliberate, controlled confidence — a man completely at home with police officers sitting in his room. Three blurred dark-uniformed officers are barely visible as dark shapes behind him. Low amber light from below. Slight low angle camera, 85mm. Oil painting. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("091", "A Victorian Gothic oil painting depicting an extreme close-up macro image from floor level looking at pale Victorian wooden floorboards. Two dark leather shoes are planted firmly and deliberately on the surface. The boards beneath the shoes look completely ordinary and undisturbed — the joins between them show nothing. Only the shoes and the floor fill the frame. Oil painting, floor level. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("092", "A Victorian Gothic oil painting depicting a medium shot from the side of a Victorian bedroom scene. Three dark-uniformed Victorian police officers are seated in wooden chairs. The tall gaunt narrator stands among them, his posture relaxed and conversational — the posture of a man completely at ease. One officer appears to be reacting with slight amusement to something. The narrator's performance of ease is entirely convincing. Warm amber bedroom. 35mm lens from the side. Oil painting. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("093", "A Victorian Gothic oil painting depicting a medium close-up of a tall gaunt man with hollow cheeks, deep-set ringed eyes, dark damp hair, dark stubble, dark charcoal jacket — still seated in the wooden chair. His expression has shifted fractionally from composure — something is wrong at the edges of the face. He is very slightly paler. His eyes have lost a fraction of their focus. The performance is still intact but something is rising through it from beneath. Amber light from below. Low angle camera, 85mm. Oil painting. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("094", "A Victorian Gothic oil painting depicting a close-up of a tall gaunt man with hollow cheeks, deep-set ringed eyes, dark damp hair, dark charcoal jacket. He is talking — his lips slightly parted — but his expression shows that the act of talking is now requiring effort. His jaw is fractionally too tight. His eyes are fractionally too focused. A man working harder than he should need to. Officers blurred behind him. 85mm lens. Oil painting. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("096", "A Victorian Gothic oil painting depicting an extreme close-up macro image of a man's hand gripping a wooden chair armrest with enormous force. The knuckles are white. The tendons on the back of the hand stand prominent. The grip is at maximum tension. A dark charcoal jacket sleeve is visible at the wrist. Warm amber candlelight from the side. Oil painting, close macro. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("097", "A Victorian Gothic oil painting depicting a medium close-up of a tall gaunt man with hollow cheeks, deep-set ringed eyes, dark damp hair, dark charcoal jacket — seated in a wooden chair. The camera is tilted 15 degrees clockwise, creating a Dutch tilt — the room behind him leans visibly at a wrong angle. His expression: the mask failing, something breaking through from beneath the composure. Officers blurred behind him at the tilted angle. Low angle camera. Warm amber light chaotic. Oil painting. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("098", "A Victorian Gothic oil painting depicting a close-up of a tall gaunt man with hollow cheeks, deep-set ringed eyes, dark damp hair, dark stubble, dark charcoal jacket. His expression: a man talking faster than he can think, trying to outrun something in his own mind. His eyes are too bright — the brightness of desperation rather than confidence. Very slight perspiration visible on the brow. Amber underlight from below. 85mm lens. Oil painting. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("100", "A Victorian Gothic oil painting depicting a medium close-up of a tall gaunt man with hollow cheeks, deep-set ringed eyes, dark damp hair, dark charcoal jacket — standing. The camera is tilted 20 degrees clockwise — the most extreme Dutch tilt — making the room behind him visibly and wrongly angled. His face: completely broken, the mask entirely gone, something erupting through. Officers barely visible as dark shapes at the distorted frame edges. Low angle camera. Oil painting. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("101", "A Victorian Gothic oil painting depicting an extreme close-up macro image filling the entire frame with a single human eye. The iris is dark grey-green — deeply dark, where the vulture eye was burning amber, this iris is cold and dark. The pupil is massively dilated, nearly consuming the visible iris — almost entirely black. The whites of the eye are visibly red-veined. Heavy dark circles are visible above and below the eye. This is the mirror image of the vulture eye — same framing, same scale, dark where the other was amber, terror where the other was diseased calm. Thick textured impasto oil brushstrokes in the iris. Widescreen 16:9 landscape format.", [EYE]),
    ("102", "A Victorian Gothic oil painting depicting a wide shot with a 14mm ultra-wide lens at floor level looking up. A Victorian bedroom with the room edges visibly distorted by the extreme wide angle lens — the walls bow outward, the perspective is exaggerated and spatially wrong. A tall gaunt man in a dark charcoal jacket stands with both arms thrown wide to his sides and his head tilted back — the posture of total abandonment, the body fully open. Dark-uniformed officers are barely visible as dark shapes at the distorted frame edges. The pale floorboards stretch away in extreme perspective beneath his feet. Amber light and cold blue light mix chaotically. This should be generated as 5 separate variations. Oil painting. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("103", "A Victorian Gothic oil painting depicting a medium close-up of a tall gaunt man with hollow cheeks, deep-set ringed eyes, dark damp hair, dark charcoal jacket. His expression: something has just been released — not relief, but a kind of collapse, the unburdening of a confession. His eyes are still wide. His jaw is working slightly. He is exposed completely, and something in the exposure is almost like relief at being finished with the pretence. 85mm lens. Oil painting. Widescreen 16:9 landscape format.", [NARRATOR]),

    # OLD MAN SHOTS
    ("009", "A Victorian Gothic oil painting depicting a close-up portrait of a very elderly frail man with a short close-cropped white beard, heavy-lidded eyes with deep wrinkles, wearing a grey-green drooping nightcap and a cream collarless Victorian nightshirt. He is seated in a plain wooden chair. His expression is completely peaceful, trusting, and gentle — the face of a man with no enemies in the world. The light source is a warm amber candle positioned below and to the right, casting golden tones upward across his face and white beard. The background is blurred warm darkness. Camera angle is high — 15 degrees above, looking slightly down. Captured with an 85mm portrait lens. Raw sienna and deep burnt umber oil painting palette with visible brushstrokes. Widescreen 16:9 landscape format.", [OLD_MAN]),
    ("010", "A Victorian Gothic oil painting depicting a medium shot of a very elderly frail man with a short white beard, grey-green drooping nightcap, cream collarless Victorian nightshirt, and worn slippers on his feet. His full figure is visible — he is seated in a plain wooden chair. His thin hands are folded in his lap. A single candle sits burning on a three-legged wooden stool directly beside him, its warm amber flame the sole light source. His expression is entirely at peace and unsuspecting. Eye level camera, 50mm lens. Warm raw sienna and amber oil painting palette with visible brushstrokes. Widescreen 16:9 landscape format.", [OLD_MAN]),
    ("034", "A Victorian Gothic oil painting depicting a close-up of a very elderly man's face in partial profile resting on a pillow, his eyes fully closed. Short white beard, grey-green drooping nightcap. His expression is complete peace — no awareness, no tension. Warm amber candlelight from the right illuminates the side of his face and his white beard in golden tones. The closed eyelid is centred prominently in the frame. High angle camera — 20 degrees above, looking down. 85mm portrait lens. Raw sienna and warm burnt umber oil painting palette. Widescreen 16:9 landscape format.", [OLD_MAN]),
    ("037", "A Victorian Gothic oil painting depicting a medium shot of a very elderly frail man with a short white beard, grey-green nightcap, cream nightshirt — bolt upright in bed, completely rigid. His eyes are wide open in near-total darkness. Both hands grip the blue-grey bedclothes tightly at his chest. His pupils are massively dilated. His face catches only the faintest trace of ambient warm light on the right cheekbone. The room is almost completely dark. His expression: frozen animal terror — the stillness of a creature that knows a predator is in the room. Eye level camera, 50mm lens. Near-total darkness, deep shadow. Oil painting. Widescreen 16:9 landscape format.", [OLD_MAN]),
    ("040", "A Victorian Gothic oil painting depicting a close-up of a very elderly frail man with a short white beard, grey-green nightcap, cream nightshirt — sitting completely rigid in bed, shown in strict profile facing the left side of the frame. His eyes are open and fixed — not looking at anything, purely listening. His neck is visibly taut with tension. His hands are clenched tightly on the blue-grey coverlet. Only a trace of warm amber candlelight comes from the right side of the frame, catching the edge of his profile. 85mm lens, eye level. Oil painting. Widescreen 16:9 landscape format.", [OLD_MAN]),
    ("041", "A Victorian Gothic oil painting depicting an extreme close-up macro image of a very elderly man's ear and the side of his head, shown in strict profile. The ear is turned toward something off-frame to the right — listening. His jaw is very slightly open, the posture of held breath and total concentration. Very aged, deeply wrinkled skin over every surface. A single trace of warm amber candlelight catches the outer cartilage of the ear. Deep warm darkness behind the head. Oil painting, warm amber tones on aged flesh against near-black. Widescreen 16:9 landscape format.", [OLD_MAN]),
    ("043", "A Victorian Gothic oil painting depicting a medium close-up of a very elderly frail man with a short white beard, grey-green nightcap, cream nightshirt — in bed, with one hand pressed flat against his own forehead. His eyes are closed. His expression shows the visible effort of trying to reason himself into calm — the facial muscles working against rising fear. Warm amber trace light on the side of his face from the right. Eye level camera, 85mm lens. Raw sienna oil painting. Widescreen 16:9 landscape format.", [OLD_MAN]),
    ("044", "A Victorian Gothic oil painting depicting a close-up of a very elderly frail man with a short white beard, grey-green nightcap — eyes reopened after an attempt at calm that has completely failed. His eyes are wider than before. The fear has returned and deepened. His expression: the absolute certainty that something is in the room with him. A trace of warm amber from the right. High angle camera, 85mm. Raw sienna oil painting. Widescreen 16:9 landscape format.", [OLD_MAN]),
    ("046", "A Victorian Gothic oil painting depicting a close-up of a very elderly frail man with a short white beard, grey-green nightcap — a large dark shadow falling diagonally across his face, dividing it precisely: one half is illuminated by warm amber candlelight, the other half is cut into sudden near-black by the shadow. His expression in the lit half: the realisation arriving, a dawning horror. 85mm lens, eye level. Extreme Caravaggio contrast. Oil painting. Widescreen 16:9 landscape format.", [OLD_MAN]),
    ("047", "A Victorian Gothic oil painting depicting a medium shot of a very elderly frail man with a short white beard, grey-green nightcap, cream nightshirt — sitting completely upright in bed with both hands pressed flat against his own chest over his heart. His profile faces strictly left. His breathing is extremely shallow. His expression: paralysed resignation — the body knows what the mind cannot yet accept. A trace of warm amber candlelight touches the right edge of his profile. 85mm lens, profile view. Oil painting. Widescreen 16:9 landscape format.", [OLD_MAN]),
    ("048", "A Victorian Gothic oil painting depicting a medium close-up of a very elderly frail man with a short white beard, grey-green nightcap — his mouth is barely parted, the lips fractionally separated, as if a sound too small to call a groan has just escaped involuntarily. His eyes are wide and absolutely fixed. His expression: a man who knows with certainty that death is standing in the room with him. Warm amber candlelight from below. High angle camera, 85mm. Raw sienna oil painting. Widescreen 16:9 landscape format.", [OLD_MAN]),
    ("049", "A Victorian Gothic oil painting depicting an extreme close-up macro image of both hands of a very elderly man, gripping folded blue-grey bedclothes. The knuckles are white with the force of the grip. The skin is papery thin and translucent — every bone and tendon is prominent beneath the surface. The grip is at absolute maximum tension. The blue-grey coverlet fabric is compressed beneath the fingers. Warm amber candlelight from the right side. Oil painting, warm amber and ochre flesh tones against blue-grey fabric. Widescreen 16:9 landscape format.", [OLD_MAN]),
    ("055", "A Victorian Gothic oil painting depicting an extreme close-up macro image in strict profile of just the neck and lower jaw of a very elderly man. The skin of the neck is papery thin and nearly translucent, and over the carotid artery area there is a barely perceptible slight depression in the skin — the visible indication of a pulse beneath the surface. White beard at the jaw edge. Deep warm amber candlelight from below. Oil painting, extreme detail in aged skin, thick visible brushstrokes. Widescreen 16:9 landscape format.", [OLD_MAN]),
    ("058", "A Victorian Gothic oil painting depicting a close-up of a very elderly frail man with a short white beard, grey-green nightcap, cream nightshirt — in strict profile facing the left side of the frame. One hand is pressed flat against his chest directly over his heart. In his neck a slight pulse is visible beneath the thin skin. His breathing produces tiny, barely perceptible chest movements. His expression: paralysed, knowing. Deep warm darkness behind him. A trace of warm amber on his face from the right side only. Eye level camera, 85mm. Oil painting. Widescreen 16:9 landscape format.", [OLD_MAN]),

    # EYE SHOTS
    ("011", "A Victorian Gothic oil painting depicting an extreme close-up macro image filling the entire frame with a single elderly eye. The iris is a burning deep amber-orange colour, almost copper-red at its very centre — like the glowing core of a live ember. A thin milky-white translucent film partially veils the surface of the iris — diseased, clouded, ancient. The pupil is small, maximising the visible burning iris. Heavy aged eyelid skin with deep wrinkles surrounds the eye. The inner corner of the eye is reddish and raw. Near-total warm amber darkness surrounds the eye. The iris is painted with thick impasto brushstrokes in layered amber, copper, and orange tones that seem to glow with inner heat. This is a deeply unsettling and unforgettable image. Widescreen 16:9 landscape format.", [EYE]),
    ("012", "A Victorian Gothic oil painting depicting an extreme close-up of an elderly man's eye in side profile. The milky translucent film over the iris catches warm amber candlelight from the right side, creating an almost iridescent surface. The burning amber-orange iris is visible at the right edge of the pupil. The aged eyelid skin is in deep profile, covered in fine wrinkles. Pure warm darkness behind the eye. Thick impasto oil painting brushstrokes in the iris. Widescreen 16:9 landscape format.", [EYE]),
    ("024", "A Victorian Gothic oil painting depicting an extreme close-up macro image filling the entire frame with a single closed elderly eyelid. Heavy, deeply wrinkled skin covers the eye completely. The vulture eye is hidden beneath. Warm amber candlelight from below-right creates subtle golden gradients across the folds of aged skin. The eyelid is perfectly and completely still. Thick impasto oil painting brushstrokes in layered raw sienna, burnt umber, and yellow ochre. The skin feels ancient and geological at this scale. Widescreen 16:9 landscape format.", [EYE]),
    ("027", "A Victorian Gothic oil painting depicting an extreme close-up macro image filling the entire frame with an elderly eye. This is even tighter than shot 011 — the copper-red core of the burning amber-orange iris is more prominent and fills more of the frame. The milky film catches light and seems to glow. The pupil is small and completely fixed. The aged eyelid skin barely visible at the extreme edges. Near-total warm darkness surrounding. Thick impasto oil brushstrokes in the iris. The eye stares at nothing. Widescreen 16:9 landscape format.", [EYE]),
    ("074", "A Victorian Gothic oil painting depicting an extreme close-up macro image filling the entire frame with a single elderly eye — but now closed. The heavy aged eyelid is shut completely. The burning amber-orange iris is hidden beneath it, but a faint trace of amber-orange warmth is visible through the thin translucent skin of the eyelid — the fire still there, but extinguished. The milky film still visible as a slight texture through the lid. Oil painting, thick brushstrokes. Widescreen 16:9 landscape format.", [EYE]),

    # BEDROOM / SETTING SHOTS
    ("023", "A Victorian Gothic oil painting depicting an extreme close-up of an old brass mantel clock face, the hands positioned precisely at midnight — both pointing straight up. The brass numerals and the hands catch warm amber candlelight that gleams on the metal surface. The clock face is cracked and aged, the glass slightly clouded. Deep warm darkness behind the clock. Macro lens, slightly elevated angle. Warm amber and deep brown oil painting palette with thick visible brushstrokes. Widescreen 16:9 landscape format.", [BEDROOM]),
    ("036", "A Victorian Gothic oil painting depicting an extreme close-up macro image of a dark Victorian tin lantern. The panel has accidentally opened wider than intended — a thick shaft of amber-gold light escapes forcefully from the gap. A thumb is visible pressed against the tin slightly off its intended position — the slip. The shaft of light is too wide, too bright, clearly accidental. Near-total darkness surrounding the lantern except for this one thick amber beam. Oil painting. Widescreen 16:9 landscape format.", [NARRATOR]),
    ("052", "A Victorian Gothic oil painting depicting a wide shot of a Victorian prison exercise yard at night. The stone walls are darkened. A single iron wall-mounted lantern at the far wall burns a small yellow flame, its circle of light tiny against the massive cold stone. The yard is completely empty. Cold blue-grey night light. 24mm lens, eye level. Oil painting in cold Payne's grey and deep blue-grey tones. Widescreen 16:9 landscape format.", []),
    ("067", "A Victorian Gothic oil painting depicting a bird's-eye macro view looking straight down at Victorian wooden floorboards. Amber-orange light glows through the seams between the boards — pressing upward from beneath, as if something with warmth lies below. The boards themselves are still and perfectly ordinary. The light at the seams is intense and pulsing with heat. Deep darkness at the frame edges. Oil painting, amber-orange at the seams against the pale wood. Widescreen 16:9 landscape format.", [BEDROOM]),
    ("069", "A Victorian Gothic oil painting depicting a medium shot of a Victorian wooden ball-top bed, now clearly pulled away from its original position against the peeling wallpaper wall. The blue-grey coverlet is disturbed, pulled unevenly, hanging off one side. The bed is not where it was before — displaced. No people visible. Warm amber candlelight. Eye level, 35mm lens. Oil painting. Widescreen 16:9 landscape format.", [BEDROOM]),
    ("077", "A Victorian Gothic oil painting depicting a bird's-eye macro view looking straight down into an open cavity beneath lifted floorboards. The wooden joists are visible — their upper surfaces lit by warm amber candlelight from above. Between the joists: deep, absolute darkness, impenetrable, the space between them completely black. The top surfaces of the joists glow warm amber while the spaces between are pure black. Oil painting. Widescreen 16:9 landscape format.", [BEDROOM]),
    ("081", "A Victorian Gothic oil painting depicting an extreme close-up macro image from slightly above of a simple round Victorian wooden tub sitting on a pale wooden bedroom floor. The amber candlelight catches only the top rim of the tub in warm light. The interior of the tub is in complete, total darkness — impenetrable black. The tub sits beside undisturbed pale wooden floorboards. Oil painting, warm amber rim against dark interior. Widescreen 16:9 landscape format.", [BEDROOM]),
    ("082", "A Victorian Gothic oil painting depicting a close-up macro image of an old brass mantel clock, the hands pointing precisely to four o'clock. The room around the clock is near-dark — the candle has burned very low, only a stub of amber flame remaining at the base of the clock. Through a high narrow window in the far background: the very faintest beginning of pre-dawn blue-grey light, barely distinguishable from darkness. Oil painting, near-dark palette with amber trace and blue-grey window. Widescreen 16:9 landscape format.", [BEDROOM]),
    ("083", "A Victorian Gothic oil painting depicting a wide shot from inside a dark corridor looking toward a heavy dark wooden front door, completely closed. The interior corridor is pure darkness. At the door seams: the very faintest hairline of pre-dawn blue-grey light bleeding through. The door itself is completely still — but the faintest impression of a recent knock is suggested by the door sitting very slightly ajar in its frame, dust disturbed around the iron knocker. 35mm lens, eye level. Near-total darkness with blue-grey trace. Oil painting. Widescreen 16:9 landscape format.", [BEDROOM]),
    ("095", "A Victorian Gothic oil painting depicting a bird's-eye macro view looking straight down at Victorian wooden floorboards. A very faint trace of amber-orange light is beginning to show at the seams between boards — barely visible, just the suggestion of warmth pressing upward from beneath. The boards look almost completely ordinary. The light at the seams is a barely perceptible glow. Oil painting. Widescreen 16:9 landscape format.", [BEDROOM]),
    ("099", "A Victorian Gothic oil painting depicting a bird's-eye macro view looking straight down at Victorian wooden floorboards. The amber-orange glow at the seams between boards is now clearly and unmistakably bright — pressing upward with intensity from beneath the floor. The boards themselves remain still and ordinary but the light at every seam is vivid and insistent. Oil painting. Widescreen 16:9 landscape format.", [BEDROOM]),

    # NARRATOR + OLD MAN SHOTS
    ("017", "A Victorian Gothic oil painting depicting a medium shot of a simple wooden table. On the right side: a very elderly frail man with a short white beard, grey-green nightcap, cream nightshirt — seated at the table with both hands wrapped gently around a cup, his expression gentle and unsuspecting. At the left edge of the frame: only the dark charcoal jacket sleeve and gaunt hand of another figure, placing something carefully on the table surface. The gesture of the hand is gentle and controlled. Warm amber morning light illuminates the scene from the right. Raw sienna and warm burnt umber oil painting palette. Widescreen 16:9 landscape format.", [NARRATOR, OLD_MAN]),
    ("029", "A Victorian Gothic oil painting depicting a wide shot from just inside a Victorian bedroom doorway threshold looking into the room. The bedroom is warm and ordinary: dark green-grey peeling wallpaper, pale wooden plank floor, wooden bed with ball-top posts and blue-grey coverlet at the right, a three-legged wooden stool with a candle burning on it, a chest of drawers at the left. An elderly man in a cream nightshirt and grey nightcap is asleep in the bed at the far right. At the left edge of the frame, barely entering the composition: a single gaunt pale hand with bony fingers, beginning to curl slowly around the wooden door frame — barely in the frame, the fingers just visible. 35mm lens, slightly elevated. Warm amber candlelight fills the room. Oil painting. Widescreen 16:9 landscape format.", [NARRATOR, OLD_MAN, BEDROOM]),
    ("033", "A Victorian Gothic oil painting depicting a wide shot from a very low angle looking through a barely-open door crack into a Victorian bedroom. The door frame cuts the left edge of the frame, slightly blurred in the foreground. Through the crack: dark green-grey peeling wallpaper, pale wooden plank floor, ball-top bed with blue-grey coverlet, a candle on a three-legged stool. An elderly man in a cream nightshirt and grey nightcap is asleep in the bed to the right. Only a fraction of the room is visible through the narrow gap. Warm amber candlelight. 24mm lens, very low angle. Oil painting. Widescreen 16:9 landscape format.", [OLD_MAN, BEDROOM]),
    ("039", "A Victorian Gothic oil painting depicting a wide shot of a Victorian bedroom seen from a high angle of 25 degrees — camera at ceiling height looking down into the room. The room is enormous from this angle. A very elderly frail man in a cream nightshirt and grey nightcap sits upright and very small in the bed at the upper right of the frame. The door is barely ajar at the far right edge. Near-total darkness fills most of the frame, the room pressing down on the old man. He is isolated and tiny. 24mm wide lens from ceiling height. Very dark palette, traces of raw sienna in the shadows. Oil painting. Widescreen 16:9 landscape format.", [OLD_MAN, BEDROOM]),
    ("042", "A Victorian Gothic oil painting depicting a wide three-quarter shot of a Victorian bedroom, slightly elevated. A very elderly frail man in a cream nightshirt and grey nightcap sits upright and very small in the bed at the right third of the frame. The remaining left two-thirds of the frame is consumed by near-total darkness — the bedroom swallowing itself in shadow, the shadows massive, solid, and architectural. Only the faintest amber light catches the old man's white beard and nightshirt on the right. Deep Caravaggio-style chiaroscuro. 35mm lens. Oil painting. Widescreen 16:9 landscape format.", [OLD_MAN, BEDROOM]),
    ("045", "A Victorian Gothic oil painting depicting a wide shot of a Victorian bedroom from the corner. The occupant of the room, a very elderly man in cream nightshirt and grey nightcap, is small in the bed at the right of the frame. On the far peeling wallpaper wall behind him: a massive shadow — the silhouette of a man's head and shoulders, hugely distorted by low candlelight, stretched and wrong, the shadow far larger than any real person. The shadow fills much of the upper left area of the frame. Only the warm amber candlelight at the base of the room gives any colour. Deep Caravaggio chiaroscuro. Oil painting. Widescreen 16:9 landscape format.", [OLD_MAN, BEDROOM]),
    ("054", "A Victorian Gothic oil painting depicting a medium shot with a divided composition. Left half of the frame: the tall gaunt narrator — dark damp hair, hollow cheeks, deep-set ringed eyes, dark charcoal jacket — in strict profile facing the right side, the cold grey prison world visible behind him. Right half of the frame: the very elderly old man — short white beard, grey-green nightcap, cream nightshirt — in strict profile facing the left side, the warm amber Victorian bedroom world visible behind him. They face each other across the centre divide but exist in completely separate worlds. The two colour palettes — cold Payne's grey and warm raw sienna — meet at the central dividing line. 50mm lens, eye level. Oil painting. Widescreen 16:9 landscape format.", [NARRATOR, OLD_MAN]),
    ("060", "A Victorian Gothic oil painting depicting a wide shot from the corner of a Victorian bedroom. A tall gaunt man in a dark charcoal jacket stands near the centre of the room, completely still, a closed dark lantern hanging in his right hand. At the right side of the frame: a very elderly frail man in cream nightshirt and grey nightcap sits completely upright in bed, rigid. The contrast in the frame: the absolute stillness and composure of the standing dark figure against the rigid terror of the old man in the bed. Warm amber candlelight from the lantern area. 35mm lens from corner. Oil painting. Widescreen 16:9 landscape format.", [NARRATOR, OLD_MAN]),
    ("062", "A Victorian Gothic oil painting depicting a wide shot from a slightly elevated angle of a Victorian bedroom. A tall gaunt man in a dark charcoal jacket is mid-stride on the pale wooden floorboard floor — one foot raised. His weight is forward. At the right side of the frame: a very elderly frail man in cream nightshirt sits upright in bed, watching the figure pace. The floorboards beneath the walking man are prominent in the foreground. Warm amber candlelight. 24mm lens, slightly elevated. Oil painting. Widescreen 16:9 landscape format.", [NARRATOR, OLD_MAN]),
    ("066", "A Victorian Gothic oil painting depicting a medium shot from directly behind a tall gaunt man in a dark charcoal jacket — his back entirely to the viewer. He stands at the side of a bed, leaning over it with both hands gripping the sides of a plain wooden chair which is pressed down toward the bed. A very elderly frail man in a white nightshirt is visible below him in the bed, his face turned away, his body pressed down. The narrator is large in the frame, the old man small beneath him. Warm amber. 50mm lens from behind. Oil painting. Widescreen 16:9 landscape format.", [NARRATOR, OLD_MAN]),
]


def generate_shots():
    """Generate all shots using Gemini API (direct, not Vertex AI)."""
    OUTPUT_DIR.mkdir(exist_ok=True)

    if not API_KEY:
        print("ERROR: Set GEMINI_API_KEY environment variable.")
        return

    # Load reference images
    print("Loading reference images...")
    ref_images = {}
    for name, path in [(NARRATOR, REF_NARRATOR), (OLD_MAN, REF_OLD_MAN),
                       (EYE, REF_EYE), (BEDROOM, REF_BEDROOM)]:
        if path.exists():
            ref_images[name] = path.read_bytes()
            print(f"  Loaded {name}: {len(ref_images[name]):,} bytes")
        else:
            print(f"  WARNING: {path} not found")

    client = genai.Client(api_key=API_KEY)

    total = len(SHOTS)
    print(f"\nGenerating {total} shots x {IMAGES_PER_PROMPT} images = {total * IMAGES_PER_PROMPT} total images")
    print(f"Model: {MODEL_ID}")
    print(f"Output: {OUTPUT_DIR.resolve()}\n")

    succeeded = 0
    failed = 0

    for idx, (shot_num, prompt, ref_types) in enumerate(SHOTS, 1):
        # Skip already generated shots
        existing = list(OUTPUT_DIR.glob(f"shot_{shot_num}_*.png"))
        if len(existing) >= IMAGES_PER_PROMPT:
            print(f"[{idx}/{total}] Shot {shot_num}: SKIPPED (already generated)")
            succeeded += 1
            continue

        print(f"[{idx}/{total}] Shot {shot_num}: {prompt[:70]}...")

        for attempt in range(MAX_RETRIES):
            try:
                # Build contents: reference images + text prompt
                contents = []
                for ref_type in ref_types:
                    if ref_type in ref_images:
                        contents.append(types.Part.from_bytes(
                            data=ref_images[ref_type],
                            mime_type="image/png",
                        ))

                contents.append(prompt)

                # Generate images
                saved_count = 0
                for img_idx in range(IMAGES_PER_PROMPT):
                    response = client.models.generate_content(
                        model=MODEL_ID,
                        contents=contents,
                        config=types.GenerateContentConfig(
                            response_modalities=["IMAGE", "TEXT"],
                            image_config=types.ImageConfig(
                                aspect_ratio="16:9",
                                image_size="2K",
                            ),
                            safety_settings=[
                                types.SafetySetting(
                                    category="HARM_CATEGORY_DANGEROUS_CONTENT",
                                    threshold="BLOCK_ONLY_HIGH",
                                ),
                                types.SafetySetting(
                                    category="HARM_CATEGORY_HARASSMENT",
                                    threshold="BLOCK_ONLY_HIGH",
                                ),
                                types.SafetySetting(
                                    category="HARM_CATEGORY_SEXUALLY_EXPLICIT",
                                    threshold="BLOCK_ONLY_HIGH",
                                ),
                                types.SafetySetting(
                                    category="HARM_CATEGORY_HATE_SPEECH",
                                    threshold="BLOCK_ONLY_HIGH",
                                ),
                            ],
                        ),
                    )

                    if response.candidates and response.candidates[0].content:
                        for part in response.candidates[0].content.parts:
                            if part.inline_data and part.inline_data.mime_type.startswith("image/"):
                                saved_count += 1
                                filename = OUTPUT_DIR / f"shot_{shot_num}_{saved_count}.png"
                                filename.write_bytes(part.inline_data.data)
                                print(f"  Saved: {filename}")

                    if img_idx < IMAGES_PER_PROMPT - 1:
                        time.sleep(1)

                if saved_count > 0:
                    succeeded += 1
                else:
                    print(f"  WARNING: No images returned")
                    failed += 1
                break  # Exit retry loop

            except Exception as e:
                err_str = str(e)
                if "429" in err_str or "RESOURCE_EXHAUSTED" in err_str or "quota" in err_str.lower():
                    wait = RETRY_DELAY * (attempt + 1)
                    print(f"  Rate limited (attempt {attempt+1}/{MAX_RETRIES}), waiting {wait}s...")
                    time.sleep(wait)
                    if attempt == MAX_RETRIES - 1:
                        print(f"  FAILED after {MAX_RETRIES} retries: {e}")
                        failed += 1
                elif "not found" in err_str.lower() or "not supported" in err_str.lower():
                    print(f"  ERROR (model issue): {e}")
                    failed += 1
                    break
                else:
                    print(f"  ERROR: {e}")
                    failed += 1
                    break

        # Delay between shots
        if idx < total:
            time.sleep(DELAY_BETWEEN_REQUESTS)

    print(f"\nDone! {succeeded} shots succeeded, {failed} failed.")
    print(f"Images saved to {OUTPUT_DIR.resolve()}")


if __name__ == "__main__":
    generate_shots()
